### ISSUE TITLE
Expo logo appears on staging app launch

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1297] opened 2020-10-21 16:44 UTC
Open the staging app on your device. Notice that a giant blurry Expo icon fills the screen until the app loads.
![Screenshot_20201019-152450_Arrival Advisor.jpg](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/29055007-71cf-4576-b87e-664ba6220d6b)
### Acceptance Criteria 
- [ ] Show a blank screen instead, or our AA logo if that's easier.

### Steps for QA: 
Side load the app on to your Android device
1. Set staging values in app.json
```
cat app.json | \
        sed s/phone_icon_android.png/phone_icon_android_staging.png/ | \
        sed s/phone_icon_ios.png/phone_icon_ios_staging.png/ | \
        sed s/org.peacegeeks.ArrivalAdvisor/org.peacegeeks.ArrivalAdvisorStaging/ > temp.json && \
        mv temp.json app.json
```
1. `expo ba`
2. Select `apk` option
3. Download apk from expo
4. Email to your android device
5. Download

**Comment by rasmus-storjohann-PG** [comment] 2020-12-16 21:32
Closing as dupe of https://github.com/pg-irc/pathways-frontend/issues/1318

**Closed by rasmus-storjohann-PG** 2020-12-16 21:32 UTC
