### ISSUE TITLE
Implement Algolia search suggestions

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1736] opened 2021-11-24 17:42 UTC
This is an algolia feature, see 5 minute "course" on how to do this: https://academy.algolia.com/guides/83ba478c-e7ab-11ea-aeed-067360dfb065/tasks/0ce69ffa-19fd-11eb-884d-067360dfb065

### Acceptance Criteria 
- [ ]  When the user types in a keyword search, suggested queries appear below the search bar, based on previously executed searches as stored and processed by Algolia

**Comment by rasmus-storjohann-PG** [comment] 2021-12-01 21:32
Hold off on investing in building this feature until we know that we will keep using Algolia for a good long while into the future.

**Comment by alysha-PG** [comment] 2022-01-19 21:21
dupe of #1175

**Closed by alysha-PG** 2022-01-19 21:21 UTC
