### ISSUE TITLE
Implement BC and MB Topic Illustrations 

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1563] opened 2021-07-30 20:40 UTC
We would like to add illustrations for the Topic Detail page. For now, each chapter has a unique illustration, so all topics under that chapter would have the same illustration. Each chapter illustration has a BC variant and an MB variant. 

The images are found [here](https://drive.google.com/drive/folders/1OWkFwBSHzyHsAuLK254upGhjtdYYp85-?usp=sharing). The suffix (- MB or - BC) tell you whether it is the MB or BC variant

Sample of what the illustration should look like in the app: [here](https://zpl.io/aRw8Xop), [here](https://zpl.io/aXy8XM8), [here](https://zpl.io/bleE6p0), [here](https://zpl.io/bWyJXYx)

### Acceptance Criteria 
- [ ] Each topic detail page should have an illustration at the top of the page.
- [ ] The illustration shown should match the province that the user is in. Eg. if the user is in BC version of the app they are shown the BC variants of the illustrations, and vice versa for MB

### Steps for QA: 
1.

**Comment by deniza-pg** [comment] 2021-08-06 21:56
Not sure if this is a bug but:

I expect to find the Education image for all the topics under Education. But if the topic is also under the things to do right away, it is not the Education image. (Things to do right away image)

This applies to other topics detail pages, too.
@cherrielam  If this is not a bug,I will close it.

**Comment by cherrielam** [comment] 2021-08-09 22:37
Hmmm this is a good point @deniza-pg. I didn't really think of this situation. Technically all the issues under "things to do right away" also belong in another category (eg. "education", "housing", etc.). I do like the idea that the topics have the other category image ("education", "housing", etc.) because it is a little more descriptive to the topic than "Things to do right away" is. Thoughts? And would this be hard to do @rasmus-storjohann-PG ?

**Comment by deniza-pg** [comment] 2021-08-30 21:29
I think it looks Ok for now. Closing now, but may visit in the future. @deniza-pg

**Closed by deniza-pg** 2021-08-30 21:29 UTC
