### ISSUE TITLE
Review and sign off on onboarding screen and text

### ISSUE THREAD

**Issue by ArtiBPG** [pg-irc/pathways-frontend#724] opened 2019-07-10 17:58 UTC
Description:
Review the onboarding screen on the staging app: 1.0.23 for content and flow.

 Issues already identified:
- Test by leaving the app and opening it again, changing language EN>Any other language. NO language selection as soon as the user opens the app. see #606. The fix the make the app remember language selection broke the language selection<>onboarding flow.
- Test onboarding in all languages for text expansion and layout, see FR situation: https://screencast.com/t/z5D8zRb64p
- The back and next buttons are not the same as the back and next buttons for the questionnaire.
- Another issue found during QA: https://github.com/pg-irc/arrival-advisor-qa/issues/13

Next steps:
Provide updates mocks and update the issue.

ACs:
Content and UX is acceptable and ready for release.

**Comment by cherrielam** [comment] 2019-07-22 22:42
Reviewing the onboarding has uncovered a few usability issues:

### UX problems
- dumping the user directly into the questionnaire is not an ideal experience because they don't get a real sense of what the app does and suddenly have to answer a bunch of questions.
- user has no ability to exit the onboarding early
- the back and next buttons feel hard to use, not as intuitive as the swiping pattern of typical onboarding

### Content problems
- content of the onboarding screens is no longer up to date. Images are placeholders.

## Recommendations
- Please see mocks here: https://zpl.io/VD4DB5r titled ONBOARDING/1 to 4. The graphics for the screen can be downloaded directly here.

1. Flow: Onboarding screens need to be **after** the welcome screen (where the user selects the language)
2. Add ability to **SKIP** in the top right corner. It is equivalent to exiting the onboarding flow. Can be replaced with an X if this is preferred? (What are your thoughts on X vs. "Skip"? @ArtiBPG @rasmus-storjohann-PG ) 
3. **Start** Button on the last screen takes you directly to the HOME screen.
4. **ALTERNATIVELY** we can remove the "Skip" button and add the "Start" button on every single screen of the onboarding flow. So the user can "Start" from any onboarding step. (Which is preferred? @ArtiBPG @rasmus-storjohann-PG 
5. Implement swiping ability to the onboarding screens for next and back. Should not need words (reduce need for translation).
6. Images and text have been updated on the screens. Please see the Zeplin link above. Most of the text has already been translated (from the website).

@ArtiBPG @rasmus-storjohann-PG I recommend reviewing & discussing before developing

**Comment by rasmus-storjohann-PG** [comment] 2019-07-23 18:22
Looks good, gave suggestions for minor tweaks to Cherrie. All strings are reused from app or website and are already translated.

**Comment by cherrielam** [comment] 2019-07-23 20:22
https://zpl.io/VD4DB5r The onboarding has now been updated and is now ready for dev @rasmus-storjohann-PG @ArtiBPG - please assign accordingly!

**Comment by bensinjin** [comment] 2019-07-25 17:54
From Rasmus regarding the manual test that failed here: https://github.com/pg-irc/pathways-frontend/issues/606#issuecomment-498369771 (referenced at the top of this issue)
> Once the user selects their language, they should no longer see the welcome screen.

So we're going to leave this working as is.

**Comment by rasmus-storjohann-PG** [comment] 2019-07-26 00:57
If you want to demonstrate the app including the welcome screen, go into settings on the device, look up the arrival advisor app, and delete all memory related to the app. This is a more complete delete all data than what is available from within the app help screen.

**Comment by jparlina** [comment] 2019-08-02 22:14
Tested on iOS 12.4 Staging V 1.1.0, server V1.3.5:

1.  Flow: Onboarding screens need to be after the welcome screen (where the user selects the language): FAILED - no language selection screen, went straight to onboarding

2. Add ability to SKIP in the top right corner. It is equivalent to exiting the onboarding flow. Can be replaced with an X if this is preferred?: PASSED - I can click X to go to Home screen directly (may not be obvious to most users, but we can just test it with some users) 

3. Start Button on the last screen takes you directly to the HOME screen: PASSED 

4. Ignore, let's not do this: ALTERNATIVELY we can remove the "Skip" button and add the "Start" button on every single screen of the onboarding flow. So the user can "Start" from any onboarding step. - @ArtiBPG @rasmus-storjohann-PG @cherrielam What was the decision here? What's the AC for me to test? 

5. Implement swiping ability to the onboarding screens for next and back. Should not need words (reduce need for translation): PASSED - I know I can swipe. It may not be as obvious (accessible) for most of our target users.

**Comment by bensinjin** [comment] 2019-08-02 22:33
Regarding @jparlina 's first point - Can we double check this was a freshly installed app and we're not dealing with language data that already existed on the device? This can be done by uninstalling /reinstalling on iOS or clearing the app data on Android.

**Comment by rasmus-storjohann-PG** [comment] 2019-08-02 23:01
Regarding point 5: Simple solution is to have the Start button visible on all the onboarding screens, e.g. see [here](https://medium.com/@the_manifest/6-user-onboarding-flows-for-mobile-apps-ef974a330ac1)

**Comment by jparlina** [comment] 2019-08-02 23:03
Thanks, @bensinjin! 
I uninstalled and re-installed the staging app, now the language selection screen comes up first. 
The language selection screen didn't show up after simply clicking "Delete all user data" on the app and exit the app. Is this the expected behaviour on iOS?

**Comment by rasmus-storjohann-PG** [comment] 2019-08-02 23:06
Yeah, "Delete all user data" does *not* delete the locale, so the welcome screen doesn't appear. That's confusing, but deleting all data is not a core user flow for the app so I'm hoping it's OK for now.

**Comment by ArtiBPG** [comment] 2019-08-07 00:04
@rasmus-storjohann-PG I uninstalled and reinstalled on Android but the language selection screen did not show up.

**Comment by cherrielam** [comment] 2019-08-07 00:42
Here are my recommendations for the onboarding screen upon testing the production version:

### User flow:
- If I had the app installed and am updating the app, then I don't have to see onboarding (it provides no added value right now to existing users).
- If I am installing the app fresh, I should see the language selection first and THEN onboarding in that language.

### UX improvements:
- Better sliding animation (in the LTR version, the screen should actually slide from left to right. You should be able to see two screens — the previous & the next — if you slide and hold your finger in the middle) - like so: https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwiz07_hwe_jAhWqyVQKHfqeAjkQjRx6BAgBEAQ&url=https%3A%2F%2Fwww.pinterest.com%2Fpin%2F271060471297761525%2F&psig=AOvVaw1cJHbK1uBXSFp6NGCv7WBl&ust=1565224475651079
- Right now when the user opens onboarding, it's a bit random and unclear that the Onboarding is Onboarding. Maybe this can be improved if the first sentence of the app screen is changed to: "**Welcome!** Arrival Advisor is your go-to guide to getting settled in your new community." @ArtiBPG @tomy-pg is "Welcome" a word that we have translations for?
- Move up the four dots at the bottom, they are easy to miss 
- Can we replace the "X" with "Skip"?
- Add a "Next" button to all the screens except the last screen which should say "Start" - like the following example: 
![image](https://user-images.githubusercontent.com/21990736/62586147-374b2e80-b871-11e9-93ff-521032fe4d3f.png)

**Comment by cherrielam** [comment] 2019-08-07 23:01
Do we want to add a way to re-access Onboarding from the side hamburger menu btw?

**Comment by bensinjin** [comment] 2019-08-08 23:19
@ArtiBPG If you're not seeing the language selection screen on fresh install that's likely a bug that wasn't introduced by this work and I'd appreciate if you could confirm it by doing one more uninstall/reinstall. The on boarding screen WILL show up for all people who have yet to see it, even those who already have the app installed, the language they see it in will be whatever language is currently saved to their device by our app.

@cherrielam I like all your suggestions and do think it should conceivably be possible to navigate back to the onboarding from an item in the hamburger menu. My only concern is about your point regarding not seeing onboarding if you already have the app installed. Off the top of my head I can't think of a reliable way to determine if the app user is new or existing so this would take a bit of thought.

**Comment by bensinjin** [comment] 2019-08-08 23:23
Maybe we could say something like: If the user has yet to set their language and have yet to see onboarding -> show them onboarding. This way we could likely avoid showing it to too many who have already installed and been using the app.

**Comment by ArtiBPG** [comment] 2019-08-12 23:21
> @ArtiBPG If you're not seeing the language selection screen on fresh install that's likely a bug that wasn't introduced by this work and I'd appreciate if you could confirm it by doing one more uninstall/reinstall. The onboarding screen WILL show up for all people who have yet to see it, even those who already have the app installed, the language they see it in will be whatever language is currently saved to their device by our app.

@bensinjin 
yes tried it again, same result. For my phone Samsung Galaxy S7 and Tomy's S9, after an uninstall and reinstall we see: Onboarding in English>Language selection.
this means a brand new Arabic speaker will never see Onboarding in Arabic.

On Jean's iPhone 7S, and an old Android 6.0.1 Nexus 5, the behaviour is as expected: uninstall>reinstall>Language Selection>Onboarding in selected language.

Let me know if you need any other phone details.

**Comment by bensinjin** [comment] 2019-08-12 23:33
Just to be clear, from Arti: "On these devices we don't see language selection even on fresh install"

**Comment by bensinjin** [comment] 2019-08-15 22:22
I've been unable to reproduce this using a Galaxy emulator with Android 9. I think I may want to try a few things with physical devices so may do this in person.

**Comment by bensinjin** [comment] 2019-08-16 19:17
This looks useful: https://stackoverflow.com/questions/43625880/uninstall-reactnative-app-clean-user-data-using-asyncstorage/44065166#44065166

**Comment by bensinjin** [comment] 2019-08-20 20:53
This is related to app backups happening via Google Drive see: https://developer.android.com/guide/topics/data/autobackup.html for details. This is how you recreate this bug:

- Install Arrival Advisor on an Android device with backup enabled and wait until backup occurs (maybe 24 hours? Reference the docs)
- Uninstall Arrival Advisor
- Reinstall Arrival Advisor during which your previously backed up settings for the app are pulled down from Google Drive, this is why we see old app settings messing thing up

You can turn this off in the Google Drive app which we demonstrated does fix the problem and should be something we do on test devices because we're often uninstalling and reinstalling builds. Existing users of AA will see the onboarding in their language after this deploy, new users will be prompted to select their language and then see the onboarding.

**Comment by bensinjin** [comment] 2019-08-20 22:20
@rasmus-storjohann-PG @ArtiBPG TLDR of the problem:

App settings (only the ones that are persisted to the device) are backed up by Google and will be pulled in on fresh app installation if you've installed this app previously. The "has seen onboarding" setting is new and cannot be pulled from the cloud so every one will see onboarding after this work is deployed. This is not a bug but truly a feature and I suggest we let it work the way it's intended.

I'm moving this issue into Review.

**Comment by bensinjin** [comment] 2019-09-13 17:16
This can probably be closed.

**Comment by tomy-pg** [comment] 2019-09-16 17:37
Summary prior to closing: 

App settings, including locales chosen, are being backed up by Google even after the app is uninstalled. Our issue about not seeing the language selection after re-installing is a _feature not a bug_. Fresh installs will see the language selector. 

Additionally here are some of the related issues that are part of Staging release 1.4.0:\
#751
#759 
#785

**Closed by tomy-pg** 2019-09-16 17:37 UTC
Labels: Show-stopper, bug, size:small, value:medium
