### ISSUE TITLE
Missing translation of UX string in French

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#2094] opened 2022-06-06 16:31 UTC
'Phone' should be in French:

![image](https://user-images.githubusercontent.com/32307781/172204259-ebdb495f-f213-4833-a756-313de0b1b8b8.png)

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.

**Comment by alysha-PG** [comment] 2022-06-06 19:46
Dupe of #1998

**Closed by alysha-PG** 2022-06-06 19:46 UTC
