### ISSUE TITLE
Implement "full" task display as outlined in designs

### ISSUE THREAD

**Issue by bensinjin** [pg-irc/pathways-frontend#78] opened 2018-05-29 00:39 UTC
This issue relies on work from https://github.com/pg-irc/pathways-frontend/pull/65 and has been based off the feature/Issue_44_tasks_and_tasks_list branch.  It assumes the data model from the aforementioned PR.

See https://projects.invisionapp.com/share/3VJJSE3NG28#/screens/299441951.  This is an initial design for a task and should be navigable to from task list items.  We've yet to fully iron out all the functionality available from these pages but we can at least get the screen in place and provide the ability to mark tasks as completed.

AC (WIP):
- Task list items should tap through to their "full" screens displaying fields from the task

The following describes the output of the "Mark as done" button from the designs. One of these three scenarios will be true:

- Task full displays should display a "Mark as done" button if the TaskUserSettings object referencing this task has its "completed" value set to 0
- Task full displays should display a  string "Task completed" if the TaskUserSettings object referencing this task has its "completed" value set to 1
- Task full displays should display an "Add to plan" button if the TaskUserSettings object referencing this task has its completed value set to 0 and it does not exist on the savedTasksList

**Comment by bensinjin** [comment] 2018-05-29 21:57
Yeah good thinking this seems reasonable.

**Comment by rasmus-storjohann-PG** [comment] 2018-05-30 16:51
Closing as duplicate of #44, will update #44 with details from this story as relevant.

**Closed by rasmus-storjohann-PG** 2018-05-30 16:51 UTC
