### ISSUE TITLE
UX Bug: Modal height

### ISSUE THREAD

**Issue by aron-chen-pg** [pg-irc/pathways-frontend#859] opened 2019-10-07 19:06 UTC
### Description of design change:
On iPhone X the “About Arrival Advisor” modal’s height is overly tall that it runs into the status bar. 

### Rationale:
If left unattended, these UI distractions would accumulate, causing the overall negative experience.

### Visual reference:
![image.png](https://images.zenhubusercontent.com/5d6ea767bc3e240001df648b/917a9e51-0c5f-4b36-a0d2-617548a327a9)

### Acceptance Criteria
- [ ] Adjust the modal height so it wouldn't run into the status bar anymore.

**Comment by rasmus-storjohann-PG** [comment] 2020-08-12 20:12
Try to define the size of the modal as % of overall screen size

**Comment by brandon-PG** [comment] 2021-07-02 20:45
Duplicate of #1409

**Closed by brandon-PG** 2021-07-02 20:45 UTC
Labels: enhancement, value:medium
