### ISSUE TITLE
UX Polish: Adjust copy of the discard modal for services review

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1352] opened 2021-01-20 21:54 UTC
> The copy on this modal should ideally be adapted to the review function. ... 
Currently is says "Discard the changes you suggested?" which is appropriate for feedback but not review.

Rasmus https://github.com/pg-irc/pathways-frontend/pull/1349#discussion_r560632421

### Acceptance Criteria 
- [x] We have new copy for the dialog: @cherrielam - see #1539
- [ ]  Copy in the discard modal is adjusted for services review

### Steps for QA: 
1.

**Comment by cherrielam** [comment] 2021-07-20 17:35
This change has been made and is part of the new strings provided to @ian-lin-PG by @alysha-PG ! :)

**Comment by rasmus-storjohann-PG** [comment] 2021-07-21 20:32
Duplicate of #1539

**Closed by rasmus-storjohann-PG** 2021-07-21 20:32 UTC
