### ISSUE TITLE
Welcome to MB Chapter has incorrect title and teaser text

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1593] opened 2021-08-18 19:40 UTC
When I look at chapters in staging app, I expect to see one entitled "Welcome to MB" with teaser text "Social customs and getting around in your community", as per this [Zeplin link](https://zpl.io/boAZqrE).

instead, I see the title "settling in MB" with teaser text "this is about settling in MB":
![File (5).jpg](https://images.zenhubusercontent.com/60b823128e6f424e93549168/ea542fa0-6409-45e8-99fd-d8bb078e4877)

Steps for QA:

- [ ] go to chapters list
- [ ] ensure title and teaser text matches zeplin

**Comment by rasmus-storjohann-PG** [comment] 2021-09-20 21:26
Duplicate of #1565

**Closed by rasmus-storjohann-PG** 2021-09-20 21:26 UTC
Labels: bug
