### ISSUE TITLE
Feedback flow UX/UI issues

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#1171] opened 2020-05-21 20:28 UTC
- [x] **HIGH priority** — Depending on the length of the service, users will have a hard time discovering the Submit button (See [video reference](https://drive.google.com/file/d/18GSQtpxiCIZEYLV8qMQ10zajJ7H7M68-/view?usp=sharing))To address this issue, the button should be sticky at the bottom of the screen.

- [ ] **HIGH Priority** — Clicking the universal back button (on Android) leads the users back to service listing without any prompts. **I need someone to explain to me what this means: Clicking on any service goes back to the feedback module instead of the service detail.** (See [video reference](https://drive.google.com/file/d/1egphF3xJjcpqz0UghAEHUejEsAsE63cp/view?usp=sharing)) The proper behaviour is when clicking on to the back button, the confirmation window (keep editing/discard) should surface. Confirming on “Discard” should lead the user back to the service detail page they were on. - **moved to issue** #1250 

- [x] **HIGH Priority** — The bottom navigation bar appears in feedback module screen depending whether the header and footer were hidden on the service listing screen. (See [video reference](https://drive.google.com/file/d/1NAUzPxQv8s99ODiYa9a3dvSYzmOn1En-/view?usp=sharing)) The proper behaviour is to remove the bottom navigation bar and have it not show up on any feedback module screen at all times.

- [x] **HIGH Priority** — Change wording on "remove service" to "This service no longer exists."

- [x] **MID Priority** — There are two buttons (back and X) that currently serve the same function. (See [video reference](https://drive.google.com/file/d/1iUNmnwSQ48WwyS1MjpSvGUM9J1nfz9sR/view?usp=sharing)) The original purpose of having the back button is so users could go back to selecting different options to suggest an update. However, this makes the whole navigation much more complex. To simplify the experience, we will remove the back button and simply replace it with the X.

- [x] **MID Priority** — After submitting feedback, when clicking onto the “Suggest an Update” button again, some previously checked details remained being selected. (See [video reference](https://drive.google.com/file/d/1te65K5-g_4Nw0swOBIctFgxe_bKU1Icz/view?usp=sharing)) The proper behaviour is to restart a new feedback module screen when the users click on the “Suggest an update” button again. 

- [x] **LOW Priority** — In the modal popup to select options to suggest (e.g., remove this service), remove the extra space and the divider at the very bottom.

- [x] **LOW Priority** — The “last verified” section isn’t an editable field. Instead of showing it in feedback module, we should remove these non-essential elements.

- [x] **LOW Priority** — Increase font size of the "Your suggestions will be reviewed by our team..."

- [x] **LOW Priority** — Reduce padding-top & -bottom of "Suggest an update" (about half of what it is right now)

- [x] **LOW Priority** — Reduce padding-right & -top of the close icon. Should fit the top edge of the "Suggest an update" and the right edge of the body text

- [x] **LOW Priority** — In the Other and Remove this service screens, align the submit button style to the existing Arrival Advisor button style.

- [x] **LOW Priority** — In the Other and Remove this service screens, remove the divider below the input field.

- [x] **LOW Priority** — In the Other and Remove this service screens, update the description text's font and font size to Avenir Book 16pt.

- [ ] **UNKNOWN Priority** — Don't show the sticky Submit button when the keyboard is shown.

**Comment by aron-chen-pg** [comment] 2020-05-25 23:30
Here are a few UI issues listed out specifically for the feedback option screen.

**Comment by aron-chen-pg** [comment] 2020-05-26 00:11
Here are a few UI issues listed out specifically for the feedback remove this service/other screen. Screenshot captured on QA version 1.34.0 
![S8 feedback - for other](https://user-images.githubusercontent.com/54860686/82848979-c4b44980-9eaa-11ea-8bcd-481944756c67.png)

**Comment by cherrielam** [comment] 2020-06-03 21:30
Did a quick review,

I unchecked "LOW Priority — In the Other and Remove this service screens, update the description text's font and font size to Avenir Book 16pt." because this is not fixed on iOS. iOS still displays in the system font.

I agree with the need for:

"UNKNOWN Priority — Don't show the discard information confirmation modal if no data has been entered in the form," and 

"UNKNOWN Priority — Disable the Submit button when there is no data in the form"

As for "UNKNOWN Priority — Don't show the sticky Submit button when the keyboard is shown." - I don't believe this is still an issue currently.

**Comment by cherrielam** [comment] 2020-06-03 21:37
I have moved the aforementioned 2 "UNKNOWN Priority" items to https://github.com/pg-irc/pathways-frontend/issues/1186, removing them in this issue

**Comment by ian-lin-PG** [comment] 2020-08-17 18:07
The back button from feedback screen returns to the service detail even if there's new information. Is the expected behaviour to have the discard/keep editing modal to appear?

Referring to the second checkbox that I have changed from checked to unchecked. I checked off some boxes that seems to have been implemented.

**Comment by tomy-pg** [comment] 2020-08-24 17:36
Staging version 1.44.0 - PASS.
Second bullet point has been moved to a new issue. It is considered a high priority bug. Not a feedback release blocker.

**Closed by tomy-pg** 2020-08-24 17:36 UTC
Labels: IRCC-Feedback
