### ISSUE TITLE
Left side margin space is not even when selecting Arabic

### ISSUE THREAD

**Issue by Farouk-PG** [pg-irc/pathways-frontend#1683] opened 2021-10-15 20:08 UTC
Switching to Arabic and looking at the topics, the margin is wider from the left side. Expected it to be even and similar to when selecting English
### Acceptance Criteria 
- [ ]  even margin space from both sides
- [ ] 
![IMG_5302](https://user-images.githubusercontent.com/89798867/137547174-c9a2ec5d-0d97-4439-a2d4-213ae0e1a177.jpg)

**Comment by rasmus-storjohann-PG** [comment] 2021-11-10 22:09
Closing as dupe of #1700

**Closed by rasmus-storjohann-PG** 2021-11-10 22:09 UTC
