### ISSUE TITLE
The capital of "settling in MB" is small 

### ISSUE THREAD

**Issue by deniza-pg** [pg-irc/pathways-frontend#1587] opened 2021-08-13 17:37 UTC
Describe the issue and expected behaviours. If this is a bug, describe the steps to reproduce the problem, what you observe, and what you expected to observe.

### Acceptance Criteria 
- [ ]  

### Steps for QA: 
1.  Open Learn all about Manitoba or recommended topics: settling in MB should be Settling in MB. It should start with a capital.

**Comment by alysha-PG** [comment] 2021-08-18 22:15
Dupe of #1593

**Closed by alysha-PG** 2021-08-18 22:15 UTC
Labels: bug
