### ISSUE TITLE
Bookmarking both services & topics

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#891] opened 2019-11-13 01:42 UTC
On the Bookmarks page, we would like users to be able to see both saved topics and services, and navigate their saved items effectively between two tabs.

### Mocks
- **Zeplin**: [View individual screens](https://app.zeplin.io/project/5bc7bfa42e72260acb03aa86/dashboard?seid=5dcb5f0e101ee1bf67e7c315)
- **Sketch Cloud**: [Clickable prototype, for flow](https://sketch.cloud/s/LMGO5/a/57enwd/play)

**Note**:
Original copy has been updated to say: 

> Save important topics _and services_...

### Acceptance Criteria 
- [ ]  Services  and topics bookmarked show up on the bookmarks page

### Steps for QA: 
1.  Delete all user data from the app
2. Bookmark a few services and topics
3. Review bookmarks page

**Comment by rasmus-storjohann-PG** [comment] 2019-12-09 21:03
Closed as a dupe of #841

**Closed by rasmus-storjohann-PG** 2019-12-09 21:03 UTC
