### ISSUE TITLE
Freeze during questionnaire for user

### ISSUE THREAD

**Issue by alysha-PG** [pg-irc/pathways-frontend#1848] opened 2022-04-12 17:53 UTC
A user of the app let me know that they tried to use the app, but on Question 6 of the questionnaire, that the app froze. Details about the user:

Phone: Samsung S20
Version of app: 1.90.0
Language this happened in: simplified Chinese

I have advised her to try again and let me know if it works or continues to freeze.

Keep this issue open to monitor to see if we keep seeing more examples of this problem.

**Comment by rasmus-storjohann-PG** [comment] 2022-05-11 20:32
Lets have somebody work with the questionnaire for 20 minutes to see if they can reproduce this crash

**Comment by rasmus-storjohann-PG** [comment] 2022-05-16 23:42
@shivangi-PG tried to reproduce this error, was not able to, closing this as CNR, cannot reproduce.

**Closed by rasmus-storjohann-PG** 2022-05-16 23:42 UTC
