### ISSUE TITLE
Lowercase Title :settling in MB

### ISSUE THREAD

**Issue by deniza-pg** [pg-irc/pathways-frontend#1562] opened 2021-07-30 16:45 UTC
Describe the issue and expected behaviours. If this is a bug, describe the steps to reproduce the problem, what you observe, and what you expected to observe.

### Acceptance Criteria 
- [ ] In the Recommended for you section: settling in MB should be Settling in MB  

### Steps for QA: 
1.  See if the title starts with uppercase

**Comment by rasmus-storjohann-PG** [comment] 2021-08-03 21:01
Dupe of https://github.com/pg-irc/pathways-frontend/issues/1565

**Closed by rasmus-storjohann-PG** 2021-08-03 21:01 UTC
