### ISSUE TITLE
Korean_Spacing

### ISSUE THREAD

**Issue by rankanglee** [pg-irc/pathways-frontend#738] opened 2019-07-17 08:53 UTC
**Describe the bug**
No spacing.

**App version**
1.0.24

**To Reproduce**
1. Go to 'Help for individuals & families'
2. Click on 'Help for families'
3. See the first three bullet points.

**Screenshots**
See attached.
![33](https://user-images.githubusercontent.com/47799302/61361676-b2eb2a00-a835-11e9-98d5-89705b64c4aa.jpeg)

**Linguistic issues**
- Current text:
-- BC주는자녀가BC주성년나이이난 19세가 될 때까지 부모가 자녀를 재정적으로 부양할 법적 책임이 있습니다. 부모는 자녀가 성년이 된 후에도 지원해야 할 수도 있습니다. 

-- 체벌은만2세가지난자녀에게만할수 있으며, 반드시 가벼운 체벌이어야 합니다.

-- 여자아이나 성인 여성의 생식기를 절단하거나 손상하면 안됩니다. 

- Suggested text:
-- BC주 는 자녀가 BC주 성년 나이이 만 19세가 될 때까지 부모가 자녀를 재정적으로 부양할 법적 책임이 있습니다. 부모는 자녀가 성년이 된 후에도 지원해야 할 수도 있습니다. 

-- 체벌은 만 2세가 지난 자녀에게만 할 수 있으며, 반드시 가벼운 체벌이어야 합니다.

-- 여자 아이나 성인 여성의 생식기를 절단하거나 손상하면 안됩니다. 

- Reason: Based on grammar.

**Smartphone (please complete the following information):**
- Device: iPhone7
- OS: iOS 12.3.1

**Comment by ian-lin-PG** [comment] 2019-07-19 19:28
Current text matches the newcomer's guide inside the markdown files. Since the newcomer's guide content is copyrighted we should not change the content without valid cause.

Googling translating the current text compared to the suggested text, the current text is reasonable. Therefore closing this issue.

**Comment by rankanglee** [comment] 2019-07-19 20:12
Hi Arti,

I just received the following email but don't quite agree with what it
says. Because I believe that it is a valid cause, not preference. It is
mandatory to have appropriate spacing in Korean according to the grammatic
rule. To give you a beter idea, current and suggested text is like below:

Current: Iamaboy.
Suggest: I am a boy.

I look forward to your response.

Thanks!
Ran

**Comment by ian-lin-PG** [comment] 2019-07-19 21:03
Reopening the issue following the suggestion. I currently don't have write access to the Newcomer's guide, pending permission from @rasmus-storjohann-PG .

**Comment by jparlina** [comment] 2019-09-17 01:55
Tested on staging V1.4.0, server 1.3.9 on iOS 12.4.1:
confirmed spacing are now consistent as suggested above (see screenshot below) 

![IMG_2389.JPG](https://images.zenhubusercontent.com/5ceeccc646b329310b95bccd/b51622b5-c8e5-4673-bbf7-5d18ec13b573)

**Closed** 2019-09-17 21:34 UTC
Labels: Translation, bug
