### ISSUE TITLE
Missing translation for UX string in UK: "Alternate name"

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#2095] opened 2022-06-06 16:40 UTC
![image](https://user-images.githubusercontent.com/32307781/172205710-955ed4d7-06f7-4095-820c-af1b1a8f1df0.png)

**Comment by alysha-PG** [comment] 2022-06-06 19:45
Dupe of #1961

**Closed by alysha-PG** 2022-06-06 19:45 UTC
