### ISSUE TITLE
Improve error message when location service is off

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [pg-irc/pathways-frontend#704] opened 2019-07-04 17:54 UTC
Error currently says "Fetching location timed out", when the real reason might be that the phone's location service is turned off. See #548. On iOs, with wifi/internet turned off (basically airplane mode), the error is "An error has occurred".

ACs:
* If service list retrieval from server fails due to location services being disabled, error message tells the user that location services need to be enabled.
* If it fails on Android due to the location service timeout bug, error message tells the user that location mode needs to be set to "High accuracy"
* If it fails on due to the phone being in airplane mode, error message tells the user that "you must be online to access service data".
* If it fails due to some server side problem (anything other than 404 error), error message tells the user there was a server side problem. Log error code for developers to be able to debug issues.
* If it fails for any other reason, generic error message tells the user that something went wrong.

**Comment by cherrielam** [comment] 2019-07-25 22:47
@rasmus-storjohann-PG @bensinjin @tomy-pg or @ian-lin-PG  - can someone send me screenshots of what these screen conditions currently look like? Unfortunately I can't generate all the issues on iPhone

One recommendation for improving the design is to help users better access their location services directly from this screen (via a button, etc.). I will have proposed mocks on Monday.

**Comment by cherrielam** [comment] 2019-07-26 02:27
Screenshots of current state:
![IMG_4505](https://user-images.githubusercontent.com/21990736/61920640-287a8880-af0f-11e9-8c0f-163702973923.PNG)
![Screenshot_20190725-155200_Arrival Advisor](https://user-images.githubusercontent.com/21990736/61920641-29131f00-af0f-11e9-9357-5e9eaeac4974.jpg)

Research: 
- https://uxplanet.org/mobile-ux-design-the-right-ways-to-ask-users-for-permissions-6cdd9ab25c27
- *Question:* does React Native have the ability to redirect the user back into their settings on iOS? @rasmus-storjohann-PG @bensinjin  @tomy-pg I understand from here that it used to be impossible but is now possible in Swift? https://stackoverflow.com/questions/4891950/how-can-i-prompt-the-user-to-turn-on-location-services-after-user-has-denied-the?rq=1

**Comment by cherrielam** [comment] 2019-07-30 01:20
Mocks are now available for empty states related to the Services Listing, please review: @ArtiBPG @rasmus-storjohann-PG 

## Overall changes:
1. Error message when services are not retrieved is now shown under the "Find a service" header. This helps to give the user the context of where their search failed. This is with the exception of the 404 message (which is the same throughout the whole app).
2. Included the option to return to settings, if this is possible.
3. Included the option to try again/refresh (right now, if the user changes their settings and goes back to the app, the page does not itself automatically reload).
4. Added visuals to make the error message more clear
5. Made the copy a little clearer and simpler for the user to understand

Here are the five states:

## 1. Location services are off:
![Location off with settings](https://user-images.githubusercontent.com/21990736/62092988-638cfc80-b22c-11e9-8058-6ffbbbc35529.png) ![Location off](https://user-images.githubusercontent.com/21990736/62092989-64259300-b22c-11e9-8ef8-275478ddad13.png)

- a) Mock in Zeplin: https://zpl.io/anLeRml - this is an option where there is a button that takes the user to their phone's Settings page to change their Location Services settings. Please see comment above.
or 
- b) Mock in Zeplin: https://zpl.io/aRGXdN0 - this is an option without Settings button

## 2. Phone is offline or airplane mode
![Offline](https://user-images.githubusercontent.com/21990736/62093043-92a36e00-b22c-11e9-9b40-7dcd04d2c63c.png)
- https://zpl.io/bJW1A7r 

## 3. Change your location services to high accuracy
![High Accuracy](https://user-images.githubusercontent.com/21990736/62093185-2b39ee00-b22d-11e9-8266-b42a712a574f.png)
- Mock in Zeplin: https://zpl.io/a8GJ17Q

## 4. Server error
![Server error](https://user-images.githubusercontent.com/21990736/62093228-4c9ada00-b22d-11e9-9555-73204e89fd30.png)
- Mock in Zeplin: https://zpl.io/V0wp1pw
- *Question*: To be honest, I'm not sure the average user understands the difference between this and the regular 404. Does it need to be a different screen? @rasmus-storjohann-PG @ArtiBPG 

## 5. 404 - Something went wrong
![404](https://user-images.githubusercontent.com/21990736/62093257-781dc480-b22d-11e9-8af4-2302d84109be.png)
- Mock in Zeplin: https://zpl.io/b6gB7oK

**Comment by ArtiBPG** [comment] 2019-07-30 05:29
@cherrielam regarding number 4- it does need to be a different screen.

**Comment by ArtiBPG** [comment] 2019-07-30 05:30
@rasmus-storjohann-PG to review and then work on this issue.

**Comment by cherrielam** [comment] 2019-08-13 19:33
@bensinjin I added a loading state screen - **keep the spinner**, but I don't think it should say "No related services found". It's fine if we want to just remove the "No related services found" and leave the spinner for the time being. 

Here is a loading state screen that would be a **nice-to-have** for the future. **(We can split this out into a separate issue for a lower priority/longer timeline if you'd like)** @rasmus-storjohann-PG thoughts?

![Loading state](https://user-images.githubusercontent.com/21990736/62971311-580e0980-bdc6-11e9-9bbf-75ef2ddf5ffb.png)

Services List/Loading state mock: https://zpl.io/VQQJE94 
Services List/loading state mock with warning about partial localization (see https://github.com/pg-irc/pathways-frontend/issues/711): https://zpl.io/29jGyzd

**Comment by cherrielam** [comment] 2019-08-13 20:51
Here is the no results screen: @bensinjin 
https://zpl.io/VxwpLmg
![No results](https://user-images.githubusercontent.com/21990736/62976465-7d544500-bdd1-11e9-9bc8-c4bd25cf6f42.png)

**Comment by ian-lin-PG** [comment] 2019-08-15 23:59
@bensinjin I can check off mock 1,3 as being complete and behave as expected. Mock 2 the icon is missing, mock 5 has the default arrival advisor logo rather than the mock image. For mock 4 I tried to direct the app to use a server that isn't running but got mock 5 instead. All of this testing is done on my android phone.

![image](https://user-images.githubusercontent.com/52009863/63134363-fee8d600-bf7d-11e9-8140-6aeaddf4ba2c.png)
![image](https://user-images.githubusercontent.com/52009863/63134367-0314f380-bf7e-11e9-97e0-794062574d43.png)

**Comment by bensinjin** [comment] 2019-08-16 16:59
@ian-lin-PG thx for testing - See comment on the PR

**Comment by jparlina** [comment] 2019-09-17 23:55
Tested on Staging V1.4.0, Server V1.3.9 on iOS 12.4.1, iPhone 7 plus:

Confirmed revised error messages:
1. When location services is disabled - PASSED
2. When phone is in airplane mode or offline - FAILED on iPhone (no error message); no issue on Android

**Comment by jparlina** [comment] 2019-09-17 23:55
@rasmus-storjohann-PG How do I QA for the following on staging?
- If it fails on Android due to the location service timeout bug, error message tells the user that location mode needs to be set to "High accuracy"
- If it fails due to some server side problem (anything other than 404 error), error message tells the user there was a server side problem. Log error code for developers to be able to debug issues.
- If it fails for any other reason, generic error message tells the user that something went wrong.

**Comment by rasmus-storjohann-PG** [comment] 2019-09-18 23:26
I don't have a good answer for this. It's really hard to make the device location service fail. Heroku has a "Maintenance mode" which temporarily makes the server unavailable, we could use that to test some of the error situations, but I think it will just return 404, so we can't try the different error flows. @ArtiBPG I think we may need to just close this out without testing in staging.

**Comment by ArtiBPG** [comment] 2019-12-05 22:42
@rasmus-storjohann-PG can you try the Heroku route you mentioned before we close this out?

**Comment by rasmus-storjohann-PG** [comment] 2019-12-11 17:55
QA: Set the staging heroku server to Maintenance mode, got this error screen in the client:
![image](https://user-images.githubusercontent.com/32307781/70646757-66e1bd00-1bfc-11ea-804e-470521ba6b21.png)

**Comment by rasmus-storjohann-PG** [comment] 2019-12-11 17:58
@jparlina I think we can consider this done, what do you think?

**Comment by jparlina** [comment] 2019-12-11 18:14
@rasmus-storjohann-PG Sure, has[ issue #832](https://app.zenhub.com/workspaces/arrival-advisor-5977956f40fbe90e67bb4155/issues/pg-irc/pathways-frontend/832) been addressed?

**Comment by ArtiBPG** [comment] 2019-12-11 23:08
we wil work on #832 later, not a priority right now

**Closed by ArtiBPG** 2019-12-11 23:08 UTC
