### ISSUE TITLE
Switching to Arabic - RTL/LTR layout issues

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1521] opened 2021-07-02 21:54 UTC
There are a few issues when switching to Arabic and then switching provinces. Tested on Staging V1.70.0 in iPhone XS. Steps to reproduce:

1. In BC version of the app, switch from English to Arabic using the side drawer
2. **In Arabic, notice that the content is still in LTR and not RTL** _<- this is a problem_
3. Switch back to English. It looks fine.
4. Close the app and re-open it.
5. **The app is now showing in English in BC but in RTL.** _<- this is a problem_
6. Switch provinces to Manitoba
7. **The app shows in English in MB but in RTL. Note that also the MB Start logo doesn't show on the MB Start card and instead it is the icon with the woman and the speech bubble?!?!** _<- this is a problem_

See video:
https://images.zenhubusercontent.com/99282566/8fbb3cd6-2b5b-4db2-aa9c-9c6805280560/rpreplay_final1625262079_mp4.mp4

### Acceptance Criteria 
- [ ] Switching to Arabic shows the app in RTL 
- [ ] When closing the app and reopening in non-Arabic language, the non-Arabic language renders properly (LTR)
- [ ] Switching from Arabic (BC) > English (BC) > English (MB) shows the MB Start card with the MB Start logo (even if you restart the app in between).

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment] 2021-07-14 20:12
Closed as duplicate of #1489.

**Closed by rasmus-storjohann-PG** 2021-07-14 20:12 UTC
Labels: Important
