### ISSUE TITLE
MB French Translation Bugs

### ISSUE THREAD

**Issue by cherrielam** [pg-irc/pathways-frontend#1638] opened 2021-10-07 17:37 UTC
- [x] 1. Typo on Help and support page: Currently the Help and support page in French is titled: "Aide **and** soutien". Change to "Aide **et** soutien"!

### Topics
- [x] 2. "Welcome to Manitoba": currently is in English. Change to "Bienvenue au Manitoba"

- [x] 3. Welcome to Manitoba/"Agences de depart et d'etablissement du Manitoba". It's called "Manitoba Start & Settlement agencies" in English, but it is called "Agences de depart et d'etablissement du Manitoba" in French. Mistakenly translated the name of Manitoba Start. Change to "Manitoba Start & Agences de d'etablissement"

- [x] 4. Family & Specialized Support"/"Soutien familial et specialise" tagline: Under header, "Support for disabilities, youth, seniors, income" appears in English, change to "Soutien aux personnes handicapées, aux jeunes, aux personnes âgées, aux revenus"

### Steps for QA: 
Make sure all changes below:

- [x] 1. Typo on Help and support page: Currently the Help and support page in French is titled: "Aide **and** soutien". Change to "Aide **et** soutien"!

### Topics
- [x] 2. "Welcome to Manitoba": currently is in English. Change to "Bienvenue au Manitoba"

- [x] 3. Welcome to Manitoba/"Agences de depart et d'etablissement du Manitoba". It's called "Manitoba Start & Settlement agencies" in English, but it is called "Agences de depart et d'etablissement du Manitoba" in French. Mistakenly translated the name of Manitoba Start. Change to "Manitoba Start & Agences de d'etablissement"

- [x] 4. Family & Specialized Support"/"Soutien familial et specialise" tagline: Under header, "Support for disabilities, youth, seniors, income" appears in English, change to "Soutien aux personnes handicapées, aux jeunes, aux personnes âgées, aux revenus"

**Comment by Farouk-PG** [comment] 2021-10-18 19:00
Just tested every required box on my end and can confirm all are fixed. It will be part of the next release.

**Comment by deniza-pg** [comment] 2021-11-02 19:59
QA:

1- Typo on Help and support page: Currently the Help and Support page in French is titled: "Aide and soutien". Change to "Aide et soutien"! 

I was expecting to see Aide et soutien"!  but it was "Aide and soutien".

3. Welcome to Manitoba/"Agences de depart et d'etablissement du Manitoba". It's called "Manitoba Start & Settlement agencies" in English, but it is called "Agences de depart et d'etablissement du Manitoba" in French. Mistakenly translated the name of Manitoba Start. Change to "Manitoba Start & Agences de d'etablissement"

Not fixed. 

In the Staging App 1.81

**Comment by alysha-PG** [comment] 2021-11-12 19:53
QA - 

1. "Aid et soutien" is now correct.

3. Is still not fixed. It reads "Agences de depart et d'etablissement du Manitoba". Change to "Manitoba Start & Agences de d'etablissement".

**Comment by brandon-PG** [comment] 2021-11-18 22:20
> QA -
> 
> 1. "Aid et soutien" is now correct.
> 2. Is still not fixed. It reads "Agences de depart et d'etablissement du Manitoba". Change to "Manitoba Start & Agences de d'etablissement".
> 
> note: reason this didn't get pushed to staging is unclear, should have worked when pushing translation strings before staging. Need to make sure it gets into staging next week.

This issue is caused by the french translation of the mb start topic in the content repo being incorrect. It cannot be fixed through weblate

**Comment by rasmus-storjohann-PG** [comment] 2021-11-22 22:22
- [ ]  This should now be fixed: It's called "Manitoba Start & Settlement agencies" in English, but it is called "Agences de depart et d'etablissement du Manitoba" in French.

**Comment by Farouk-PG** [comment] 2021-11-22 23:00
moving to in review as applicable change was added.

**Comment by alysha-PG** [comment] 2021-11-27 00:35
FIXED!!

**Closed by alysha-PG** 2021-11-27 00:35 UTC
Labels: Translation, Show-stopper-MB
