### ISSUE TITLE
UX Polish: Welcome screen: app should not reboot and take user to onboarding when changing locale to Arabic

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/pathways-frontend#1450] opened 2021-03-25 17:00 UTC
Clear your expo / AA app memory then:
1. On the welcome screen, select French.
- notice that the app refreshes and the app strings are translated
2. On this same screen, select Arabic.
- notice that the app refreshes and takes you directly to the app onboarding

The app should not reboot until the user clicks start. The functionality is inside `saga/locale.ts`. Because of how that saga works, the easiest way to make this work with the welcome screen is to maintain the currently selected language local to the welcome component (i.e. not send it to redux) until the Submit button is hit. That means that the welcome screen will not change locale at all while the user is interacting with it.

### Acceptance Criteria 
- [ ]  App does not reboot and take user to onboarding when changing to Arabic

### Steps for QA: 
1.

**Comment by rasmus-storjohann-PG** [comment] 2021-04-29 22:49
Closing as a duplicate of #1473

**Closed by rasmus-storjohann-PG** 2021-04-29 22:49 UTC
